### ISSUE TITLE
Support input types other than text

### ISSUE THREAD

**Issue by kigorw** [grnadav/databind#1]
You have such string:
['text', 'textarea', 'select-one']

But there are some other types 
color
date
datetime
datetime-local
email
month
number
range
search
tel
time
url
week
http://www.w3schools.com/html/html5_form_input_types.asp

**Comment by grnadav** [comment]
yup, all not being taken care of. i'd push them for 0.3.0

**Comment by grnadav** [comment]
all taken care of but datetime, which is only supported by IE
