### ISSUE TITLE
Binding to non-input model doesn't work in FF

### ISSUE THREAD

**Issue by jonathancochran** [grnadav/databind#12]
Binding to non-input elements like`<span data-key="model"></span>` or `<div data-key="example"></div>` doesn't work in firefox. Works in chrome and IE. Binding to `<input />` seems to work fine though...

**Comment by grnadav** [comment]
Hey.
Thanks for the bug report. unfortunately these days I'm out of capacity to fix this.
a PR would be hugely appreciated!

**Comment by jonathancochran** [comment]
The issue lies in line 484 in DataBind.js. To fix replace el.innerText with el.textContent:

``` js
        // else assume non-input element
        if (isSetter) {
            el.textContent = newVal;
        }

        return el.textContent;
```
