### ISSUE TITLE
Why integrate WatchJS

### ISSUE THREAD

**Issue by englishextra** [grnadav/databind#17]
I already use it, so having two watchJS is a bit confusing.

Is it possible to provide
databind.js
databind.pkgd.js

?

**Comment by grnadav** [comment]
That a good idea.
Only caveat I see is versioning collision in case of breaking changes in watchJS, in which case it'd silently make databind not work.

As this repo. is no longer maintained (and even if it were :) ), feel free to fork it do as you like with it.

**Comment by englishextra** [comment]
@grnadav fair enough thanks
