### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by Integralist** [grnadav/databind#3]
I know this is on the potential 'upcoming' features list but thought I'd raise and issue just so it's noted somewhere that users are very much interested in IE8 support.

**Comment by grnadav** [comment]
Thanks @Integralist ! 
I wasn't aware of the usage this has on IE8.

**Comment by girvo** [comment]
I'd like to throw my hat in the ring, where I work at JuniorCru we're looking for a library for two-way databinding, and DataBind is perfect, except we have to be able to support IE8 (and considering it's got 10% of the market in Australia, we can't really afford to drop it). So, consider this our :+1:

**Comment by grnadav** [comment]
Hi Josh!

Thank you for that, it really made me feel like this project was worth the time.
Unfortunately, these days I'm in over my head w\ other stuff and so this one (as did many other projects) found it's way to the unmaintained projects list :(

If you wish, you could fork this and add support for IE8, of course a pull request would be more than appreciated (and a mention on the README page of course).

In any case, thanks again for your approach. It really means a lot to me :)

Thanks
Nadav
