### ISSUE TITLE
Why define data attributes?

### ISSUE THREAD

**Issue by xeoncross** [grnadav/databind#5]
What if you modified the syntax to make the databind "smarter"? So instead of 

```
<div id="id1">
    <div>
        <textarea data-key="k1" rows="5" cols="30"></textarea>    
    </div>
    <div data-key="k2" ></div>
</div>

var model = {
    k1:  'Some text',
    k2:  'Some Div'
};
DataBind.bind( $('#id1'), model );
```

Seems like the `data-key` definitions are repetitive (though easier to listen for changes too). What if you just looked at the node values to see if they matched the model keys?

```
<div id="id1">
    <div>
        <textarea rows="5" cols="30">k1</textarea>    
    </div>
    <div>k2</div>
</div>

var model = {
    k1:  'Some text',
    k2:  'Some Div'
};
DataBind.bind( $('#id1'), model );
```

**Comment by grnadav** [comment]
Well, thats an interesting idea, and I have to admit I considered it when I
first thought of the idea,

the reasons I did not go with that are:
1. Until javascript runs, the values of the fields are erroneous, sometimes
even illegal (say a range value of "k1" where values of 0 to 10 are allowed)
2. Multiple fields cannot have same initial values (i.e. two text fields w\
value k1)
3. Semantically incorrect - the values of the fields should not denote
their identification.
4. Similar to 3, but derived from it that values might (and will...)
change, which will make this approach less resilient to changes in the code
5. Readability - as a reader of the HTML code you'd see a value (say "k1")
and not know why... (this of course related to #3 and #4 above)

Does this make sense to you?

Nadav

On Thu, Jul 10, 2014 at 6:23 PM, David Pennington notifications@github.com
wrote:

> What if you modified the syntax to make the databind "smarter"? So instead
> of
> 
> <div id="id1">
>     <div>
>         <textarea data-key="k1" rows="5" cols="30"></textarea>
>     </div>
>     <div data-key="k2" ></div>
> </div>
> 
> var model = {
>     k1:  'Some text',
>     k2:  'Some Div'
> };
> DataBind.bind( $('#id1'), model );
> 
> Seems like the data-key definitions are repetitive (though easier to
> listen for changes too). What if you just looked at the node values to see
> if they matched the model keys?
> 
> <div id="id1">
>     <div>
>         <textarea rows="5" cols="30">k1</textarea>
>     </div>
>     <div>k2</div>
> </div>
> 
> var model = {
>     k1:  'Some text',
>     k2:  'Some Div'
> };
> DataBind.bind( $('#id1'), model );
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/grnadav/databind/issues/5.

## 

Codesmith
