### ISSUE TITLE
Binding select

### ISSUE THREAD

**Issue by lrkwz** [grnadav/databind#7]
Which is the best way to bind to a select object? i.e. make one of the available options "selected"

**Comment by grnadav** [comment]
Check out the demo page:
http://codepen.io/grnadav/pen/ptJKg
It has an example of how to bind select elements, single and multiple choice.

**Comment by lrkwz** [comment]
Sorry my fault ...  I bound the controls before populating the options :-) jQuery.when() saved me

**Comment by grnadav** [comment]
:)
