### ISSUE TITLE
Variable deep binding

### ISSUE THREAD

**Issue by lrkwz** [grnadav/databind#8]
(live sample at http://jsfiddle.net/lrkwz/q3tb9b0o/7/)
Suppose I have a model with an array of elements such as:

``` javascript
var user = {
        name: "Lrkwz",
        terms_conds: [
            {
                id: 100,
                accepted: true
            }, {
                id: 103,
                accepted: false
            }
    ]
};
DataBind.bind($('#myform'), user);
```

how would you bind it to a form?

``` html
<form id="myform">
    <label>Your name
        <input id="name" data-key="name" />
    </label>
    <label>Accept privacy 1
        <input id="100" data-key="terms_conds.accepted" type="checkbox" />
    </label>
    <label>Accept privacy 2
        <input id="103" data-key="terms_conds.accepted" type="checkbox" />
    </label>
</form>
```

NOTE: the number of <input type="checkbox"> is the same of the number of elements in terms_conds

**Comment by grnadav** [comment]
Well, currently this is not supported :(
sure sounds like a needed feature though. perhaps for #0.4.0

p.s.
You're more than welcome to contribute :)

**Comment by lrkwz** [comment]
Any suggestion on how to doit "manually".
I will be glad to contribute ... as soon as I get out of the s I'm in now :-)

**Comment by grnadav** [comment]
Well, the issue here of course is that binding to arrays is not supported. you could have the values in different variables :/

**Comment by grnadav** [comment]
Added in 0.4.0. 
The fiddle now works: http://jsfiddle.net/q3tb9b0o/8/
Closing
